config/routes.rb
DareRails::Application.routes.draw do
  
  get "web_app/sf"

  get "web_app/mv"

  get "web_app/disrupt"

  get "web_app/pa"

  get "web_app/sv"

  get "users/new"

  get "static_pages/aboutus"

  #match '/signup'  => 'users#new' 
  resources :challenges do
    resources :submissions
  end
  resources :users

  root to: "static_pages#home"

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/models/challenge.rb
# == Schema Information
#
# Table name: challenges
#
#  id                    :integer          not null, primary key
#  title                 :string(255)
#  description           :string(255)
#  brand_name            :string(255)
#  brand_logo_url        :string(255)
#  hero_img_url          :string(255)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  challenge_type        :string(255)
#  challenge_reward      :string(255)
#  challenge_location    :string(255)
#  brand_description     :string(255)
#  challenge_cover_photo :string(255)
#

class Challenge < ActiveRecord::Base
  attr_accessible :brand_name, :title, :description, :brand_logo_url, :challenge_reward, :challenge_type, :challenge_location, :brand_description, :challenge_cover_photo
  has_many :submissions
  
  validates :brand_name, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true  
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def new
    @challenge = Challenge.new
    @challenges = Challenge.all()
  end

  def create
    @challenge = Challenge.new(params[:challenge])
    
    if @challenge.save
      redirect_to challenges_path    
    else
      render 'new'
    end
  end
  
  def index
    @challenges = Challenge.all()
    
    respond_to do |format|
        format.html 
        format.json { render :json => @challenges }
        format.js { render_json @challenges.to_json }
    end            
  end
  
  def show
    @challenge = Challenge.find(params[:id])
    @submissions = @challenge.submissions
  end
  
  def edit
    @challenge = Challenge.find(params[:id])
    @challenges = Challenge.all()
  end
  
  def update
    @challenge = Challenge.find(params[:id])    
    
    if @challenge.update_attributes(params[:challenge])    
      redirect_to challenges_path    
    else
      render 'edit'
    end 
  end
  
  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    redirect_to challenges_path
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/edit.html.erb
<%= form_for(@challenge, :html => { :class => "well form_well"} ) do |f| %>

  <%= f.label :brand_name, 'Brand:' %>
  <%= f.text_field :brand_name, :autofocus => "autofocus" %>

  <%= f.label :brand_description, 'Brand Description:' %>
  <%= f.text_field :brand_description, :autofocus => "autofocus" %>

  <%= f.label :challenge_cover_photo, 'Challenge Cover Photo:' %>
  <%= f.text_field :challenge_cover_photo, :autofocus => "autofocus" %>

  <%= f.label :title, 'Title:' %>
  <%= f.text_field :title %>

  <%= f.label :description, 'Description:' %>
  <%= f.text_area :description, :rows => "3" %>

  <%= f.label :brand_logo_url, 'Brand Logo url:' %>
  <%= f.text_area :brand_logo_url, :rows => "1" %>

  <%= f.label :challenge_reward, 'Rewards:' %>
  <%= f.text_area :challenge_reward, :rows => "1" %>

  <%= f.label :challenge_location, 'Challenge Location:' %>
  <%= f.text_area :challenge_location, :rows => "1" %>
<hr>
<p>Current Challenge locations</p>
    <% @challenges.each do |challenge| %>
      <%= challenge.challenge_location %>
    <% end %>
<hr>
<p>Challenge Type:</p>
  <%= f.label :challenge_type, 'Web' %>
  <%= f.radio_button(:challenge_type, "Web") %>
  
  <%= f.label :challenge_type, 'Mobile' %>
  <%= f.radio_button(:challenge_type, "Mobile") %>
</br>
  <%= f.submit "Submit", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/challenges/index.html.erb
<div>
	<br/>
	<a href="<%= new_challenge_path %>">+Create New</a>
	</br></br></br>
	<table class="table table-bordered table-striped">
	  	<thead>
		  <tr>
			<th>Brand</th>
			<th>Brand Description</th>
			<th>Challenge Cover Photo</th>
			<th>Title</th>
			<th>Description</th>
			<th>Brand Logo</th>
			<th>Rewards</th>
			<th>Challenge Location</th>
			<th>Challenge Type</th>
			<th></th>
		  </tr>
		</thead>
		<tbody>
		<% @challenges.each do |challenge| %>
		  <tr>
			<td><%= challenge.brand_name %></td>
			<td><%= challenge.brand_description %></td>
			<td><%= challenge.challenge_cover_photo %></td>
			<td><%= challenge.title %></td>
			<td><%= challenge.description %></td>
			<td><%= challenge.brand_logo_url %></td>
			<td><%= challenge.challenge_reward %></td>
			<td><%= challenge.challenge_location %></td>
			<td><%= challenge.challenge_type %></td>
			<td width="150px" style="text-align:center">
				<%= link_to 'Show', challenge_path(challenge.id) %>
				&nbsp;|&nbsp;
				<%= link_to 'Edit', edit_challenge_path(challenge.id) %>				
				&nbsp;|&nbsp;
				<%= link_to 'Delete', challenge_path(challenge.id), :confirm => "Are you sure?", :method => :delete %>
			</td>
		  </tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/challenges/new.html.erb
<%= form_for(@challenge, :html => { :class => "well form_well"} ) do |f| %>

  <%= f.label :brand_name, 'Brand:' %>
  <%= f.text_field :brand_name, :autofocus => "autofocus" %>

  <%= f.label :brand_description, 'Brand Description:' %>
  <%= f.text_field :brand_description, :autofocus => "autofocus" %>

  <%= f.label :challenge_cover_photo, 'Challenge Cover Photo:' %>
  <%= f.text_field :challenge_cover_photo, :autofocus => "autofocus" %>

  <%= f.label :title, 'Title:' %>
  <%= f.text_field :title %>

  <%= f.label :description, 'Description:' %>
  <%= f.text_area :description, :rows => "3" %>

  <%= f.label :brand_logo_url, 'Brand Logo url:' %>
  <%= f.text_area :brand_logo_url, :rows => "1" %>

  <%= f.label :challenge_reward, 'Rewards:' %>
  <%= f.text_area :challenge_reward, :rows => "1" %>

  <%= f.label :challenge_location, 'Challenge Location:' %>
  <%= f.text_area :challenge_location, :rows => "1" %>
<hr>
<p>Current Challenge locations</p>
    <% @challenges.each do |challenge| %>
      <%= challenge.challenge_location %>
    <% end %>
<hr>
<p>Challenge Type:</p>
  <%= f.label :challenge_type, 'Web' %>
  <%= f.radio_button(:challenge_type, "Web") %>
  
  <%= f.label :challenge_type, 'Mobile' %>
  <%= f.radio_button(:challenge_type, "Mobile") %>
</br>
</br>

  <%= f.submit "Submit", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/challenges/show.html.erb
<h2><%= @challenge.brand_name %> | <%= @challenge.title %></h2>

<%= @challenge.description %>
<br/><br/>

<h4>Submissions (<%= @submissions.count %>)</h4>
&nbsp;&nbsp;<a href="<%= new_challenge_submission_path(@challenge.id) %>">+Create New</a>
<br/><br/>

<div class="span5">
<ul class="submissions">
	<% @submissions.each do |submission| %>
		<li class="submission">
			<img height="100px"  src="<%= submission.content_url %>">
			<br/>
			<%= submission.description %>
			<br/>
			<%= link_to 'Show', challenge_submission_path(@challenge.id, submission.id) %>
			&nbsp;|&nbsp;
			<%= link_to 'Delete', challenge_submission_path(@challenge.id, submission.id), :confirm => "Are you sure?", :method => :delete %>
		</li>
	<% end %>
</ul>
</div>